### PR TITLE
Add Sabertooth firmware module

### PR DESCRIPTION
**Pull request by aaroncohen73**
This should be a fairly complete implementation. However, `uart_tx_in_progress` still needs to be implemented at a later time.

### CODE REVIEW

**Comment by NickAmes** [comment]
Looks good, except for a couple issues:
You can remove the wait at the end of sabertooth_tx(). The saberteeth don't share their uart (anymore) and the uart module will handle the wait if another write occurs while one is in progress.

Add the adc.o module to your makefile to get rid of the conflict.

Add a sabertooth_init() function that calls uart_enable() for 9600 baud.

**Comment by aaroncohen73** [comment]
@NickAmes So we have 4 saberteeth, each using one of the 4 UART channels?

**Comment by NickAmes** [comment]
No, all six saberteeth are connected to the same UART.

**Comment by aaroncohen73** [comment]
Never mind, I see what you meant now

**Pull request merged**
